### ISSUE TITLE
docker-compose down logs ERROR and WARNING

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arb-sdk#1]
### Error:

1. Run a demo dapp in dev mode i.e. `arb-deploy contract.ao 3 -d`
2. Delete the `compose` folder
3. Run the dapp again in normal mode i.e. `arb-deploy contract.ao 3`

### Warning:

4. Halt the dapp with Ctrl-C
5. Run the dapp again in normal mode i.e. `arb-deploy contract.ao 3`

### Error:

Attempting to run docker-compose down will fail because the compose folder has been deleted:

```
$ docker-compose -f ./arb-docker-compose.yml down -t 0

ERROR: build path /Users/ughe/workspace/master/pet/compose/arb-ethbridge either does not exist, is not accessible, or is not a valid URL.
```

### Warning:

If a docker-compose.yml file exists but no network is found, there will be a warning:

```
$ docker-compose -f ./arb-docker-compose.yml down -t 0

Removing network pet_default
WARNING: Network pet_default not found.
```

## Possible Solution

Currently these errors are just ignored. One solution would be to remove the `docker-compose down` command and just keep removing all containers and images that have `arb-validator` and `arb-ethbridge` in the name (as already occurs).

**Comment by hkalodner** [comment]
This is no longer applicable in the change to our monorepo.
